kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer 
  selector:   
    app: frontend
    tier: web 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}