kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:  #labels are used as selectiors
    app: mysql
    tier: mysql
    project: expense
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306        
        