apiVersion: v1
kind: Pod
metadata:
  name: tolerence2
  labels:
    purpose: "tolerence-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx