kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      request:
        memory: "68mi"
        cpu: "100m"
      limit:
        memory: "128mi"
        cpu: "150m"   