apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-d
  labels: 
    app: frontend
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: hussainbi/nginx:1.0
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  labels:    
    app: frontend
    tier: web  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007    

