apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    env: dev
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      env: dev
      tier: backend
  template:
    metadata:
      name: backend
      labels:
        project: expense
        env: dev
        tier: backend    
    spec:
      containers:
      - name: nginx
        image: hussainbi/backend:1.0.0         
---
kind: Service
apiVersion: v1
metadata:
  name: backend-lb
spec:
  selector:
    project: expense
    env: dev
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 


